### ISSUE TITLE
[client] build issue

### ISSUE THREAD

**Issue by gyim1345** [dev-answer/dev-answer#45]
## What

서버 없다고 가정하고 script에 있는 yarn build 실행해서 얻은 build 파일의 index.html 을 열어 봤을때

### expected
![expected](https://user-images.githubusercontent.com/57941049/127254973-10e48f6e-6b14-458d-b1e8-0cc51a09bbae.PNG)
![expected 2](https://user-images.githubusercontent.com/57941049/127254977-99432bd3-6b33-4ee4-8ffa-d50fb96241d6.PNG)

### result

![result](https://user-images.githubusercontent.com/57941049/127254981-7f78ba71-687c-4727-bdbd-836ff0d72132.PNG)
![result2](https://user-images.githubusercontent.com/57941049/127254984-9d8ea26e-fd01-430b-b044-6173ade12ee2.PNG)

### 코드 테스트용 수정 사항 

코드 수정은 텍스트만 넣었습니다

![index](https://user-images.githubusercontent.com/57941049/127254990-d26e8049-89ab-4cf6-b8df-c63f66b8f8f2.PNG)
![app](https://user-images.githubusercontent.com/57941049/127254993-55997050-05d8-4c56-bf75-dbc296dc56e2.PNG)
![example](https://user-images.githubusercontent.com/57941049/127254994-0f22eb65-ff9d-46f6-aecd-6e745990381e.PNG)

### note
- 원래 대로라면 index.html을 열었을때 위 expected(yarn start로 얻은 결과물) 처럼 나와야하는데 result처럼 나오게 된다.

### 추가로 해본거

ExamplePage 바로 불러오기

#### 코드 
![추가로 해본거 코드](https://user-images.githubusercontent.com/57941049/127255835-0ea654d4-115a-414f-8fd9-331c9036af09.PNG)

#### 결과물
![추가로 해본거 결과](https://user-images.githubusercontent.com/57941049/127255859-dddc3d65-3f4e-4470-af36-f30286ca7b35.PNG)

- router 설정이 이상할수도?

**Comment by passwd10** [comment]
코드를 봐야 알것같은데욥..!

**Comment by gyim1345** [comment]
업데이트 했습니다!
